name: Deploy React App via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build React
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp # or ftp, ftps – use what Hostinger supports
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./build/
          server-dir: /public_html/
