name: Test SSH Connection to Hostinger

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_SERVER_IP }}
          username: ${{ secrets.HOSTINGER_SERVER_USER }}
          port: ${{ secrets.HOSTINGER_SERVER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            whoami
            ls -al /home/${{ secrets.HOSTINGER_SERVER_USER }}/public_html
