name: Deploy React App via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build React
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.25.124.251
          username: u450361634.techsaraz.in
          password: NewVision@2025
          protocol: ftp
          port: 21
          local-dir: ./build/
          server-dir: /public_html/
